//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymHub.DataAccess.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.TraineeStatistics = new HashSet<TraineeStatistic>();
            this.TrainingSchedules = new HashSet<TrainingSchedule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TraineeStatistic> TraineeStatistics { get; set; }
        public virtual ICollection<TrainingSchedule> TrainingSchedules { get; set; }
    }
}
