//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymHub.DataAccess.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSchedule
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ProgramId { get; set; }
        public int ExerciseId { get; set; }
    
        public virtual Exercise Exercises { get; set; }
        public virtual Program Programs { get; set; }
    }
}
