//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymHub.DataAccess.DomainModels
{
    public partial class TraineeCheckIn
    {
        public int Id { get; set; }
        public int TraineeId { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
    
        public virtual Trainee Trainees { get; set; }
    }
}
