//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymHub.DataAccess.DomainModels
{
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public Trainee()
        {
            this.TraineeCheckIns = new HashSet<TraineeCheckIn>();
            this.TraineeStatistics = new HashSet<TraineeStatistic>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual ICollection<TraineeCheckIn> TraineeCheckIns { get; set; }
        public virtual ICollection<TraineeStatistic> TraineeStatistics { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
